- name: Replace domain name
  replace:
    path: /etc/nginx/sites-available/{{ vhost_name }}.conf
    regexp: "mydomain.name"
    replace: "{{ vhost_name }}"
- name: Create symbolic link 
  file:
    src: /etc/nginx/sites-available/{{ vhost_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ vhost_name }}.conf
    state: link
- name: "Reloaded Nginx"
  systemd: 
    name: nginx
    state: reloaded
    enabled: yes