- name: Certbot install task
  import_tasks: install.yml
- name: Certbot configure task
  import_tasks: reverse.yml
  when: {{ vhost_type }} == "Reverse Proxy"
- name: Certbot configure task
  import_tasks: php-app.yml
  when: {{ vhost_type }} == "Application PHP"