- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: Create a new  DB called AnsibleDB
  mysql_db: 
    name: ansible 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
- name: Create ansible db user
  mysql_user: 
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    priv: 'ansible.*:ALL,GRANT'
    state: present