- name: Install MySQL packages
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - mariadb-server
    - MySQL-python
- name: Start mysql server and enable it on reboot
  systemd: 
    name: mariadb 
    state: started
    enabled: yes