- name: upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Install some packages
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - yum-utils
    - policycoreutils-python
    - wget
    - epel-release
    - git
    - firewalld
    - zip
    - unzip
- name: Add REMI repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
